[build]
  # the command you run to build this file
  command = "npm run build"
  # netlify-lambda builds to this folder AND Netlify reads
  # functions from here
  functions = "built-lambda"
  # create-react-app builds to this folder, Netlify should
  # serve all these files statically
  publish = "build"

# this rule will serve the index.html instead of giving a 404
# no matter what URL the browser requests
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
