const colors = {
  black: '#202333',
  blue: '#3db8db',
  darkBlue: '#186a81',
  darkGreen: '#00a666',
  green: '#00b777',
  grey: 'rgba(0, 0, 0, 0.2)',
  lightBlue: '#e6ebef',
  lightPurple: '#f2eff7',
  offWhite: '#f7f9f6',
  purple: '#6d60b0',
  white: '#fff',
};

export default {
  background: colors.lightBlue,
  border: colors.grey,
  borderActive: colors.blue,
  borderRadius: '0.25rem',
  boxShadow: '0 0.375rem 0.75rem -0.5rem rgba(0, 0, 0, 0.1)',
  boxShadowLarge: '0 0.5rem 1rem rgba(0, 0, 0, 0.1)',
  breakpointS: '600px',
  breakpointM: '900px',
  breakpointL: '1200px',
  button: colors.blue,
  buttonActive: colors.darkBlue,
  buttonText: colors.white,
  consentBackground: colors.offWhite,
  header: colors.lightBlue,
  headerText: colors.text,
  input: colors.white,
  link: colors.darkBlue,
  maxWidth: '1140px',
  text: colors.black,
  transition: '0.3s cubic-bezier(1, -0.65, 0, 2.25)',
  transitionEase: '0.3s ease-in-out',
};
